name: 'ParticlesDart'
version: 0.0.1
description: Play with particles in Html5 canvas using Dart
author: Albert Manyà <albertmp@eml.cc>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git

transformers:
- dart_to_js_script_rewriter
